channels:
  - conda-forge

dependencies:
  - python=3.7
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.3
  - cmake=3.21
  - qt=5.12  # conda-forge does not have 5.13.2 available
  - pip
  - moderngl 
  - pip:
    - gym3==0.3
    - numpy==1.17
    - gym
    - filelock==3.0
